library(es.dif) 
library(jmv)
library(effectsize)
alpha <- 0.05
m <- seq(160,185,2.5)
f <- seq(150,170,2.5)
nm <- length(m)
nf <- length(f)
estatura <- c(m,f)
grupo <- factor(c(rep("Masculino",nm),
           rep("Feminino",nf)))
dados <- data.frame(grupo,estatura)
sink("Verificacao de tamanho de efeito.txt")
cat("Amostra original\n")
print(fit <- t.test(estatura~grupo,data=dados))
print(fit2 <- oneway.test(estatura~grupo,data=dados),var.equal=FALSE)
df <- as.numeric(fit$parameter)
t <- fit$statistic
F <- as.numeric(fit$statistic^2)
cat("Tamanho de efeito\n")
eta2 <- F/(F+df)
cat("\tR^2 = F/(F+df) = eta^2 de Cohen = ",eta2,"\n",sep="")
eta2e <- effectsize::eta_squared(fit2)$Eta2
cat("\tR^2 = eta^2 de Cohen (effectsize::eta_squared) = ",eta2e,"\n",sep="")
out <- es.dif::es.d(m,f)
cat("\nOriginal\n")
print(m)
print(f)
d <- as.numeric(out[1,2])
cat("\td de Cohen (es.dif::es.d) =", d,"\n")
print(effectsize::interpret_d(d,rules = "cohen1988"))
print(effectsize::interpret_d(d,rules = "sawilowsky2009"))
print(effectsize::interpret_d(d,rules = "gignac2016"))
print(effectsize::interpret_d(d,rules = "lovakov2021"))
d <- psych::cohen.d(estatura,grupo)$cohen.d[2]
cat("\td de Cohen (psych::cohen.d) =", d,"\n")
print(effectsize::interpret_d(d,rules = "cohen1988"))
print(effectsize::interpret_d(d,rules = "sawilowsky2009"))
print(effectsize::interpret_d(d,rules = "gignac2016"))
print(effectsize::interpret_d(d,rules = "lovakov2021"))
cat("\nSelecao de modelo\n")
R2aj <- (F-1)/((F-1)+df+1)
cat("\tR^2 ajustado =", R2aj,"\n")
omega2 <- (F-1)/((F-1)+df+2)
cat("\tomega^2 = (F-1)/((F-1)+df+2) = ", omega2,"\n")
print(o2 <- effectsize::omega_squared(fit2)$Omega2)
cat("\tomega^2 (effectsize::omega_squared) = ", o2,"\n\n")
cat("Amostra duplicada\n")
dados <- rbind(dados,dados)
m <- dados$estatura[dados$grupo=="Masculino"]
f <- dados$estatura[dados$grupo=="Feminino"]
nm <- 2*nm
nf <- 2*nf
print(fit <- t.test(estatura~grupo,data=dados))
print(fit2 <- oneway.test(estatura~grupo,data=dados),var.equal=FALSE)
df <- as.numeric(fit$parameter)
t <- fit$statistic
F <- as.numeric(fit$statistic^2)
cat("Tamanho de efeito\n")
eta2 <- F/(F+df)
cat("\tR^2 = F/(F+df) = eta^2 de Cohen = ",eta2,"\n",sep="")
eta2e <- effectsize::eta_squared(fit2)$Eta2
cat("\tR^2 = eta^2 de Cohen (effectsize::eta_squared) = ",eta2e,"\n",sep="")

out <- es.dif::es.d(m,f)
cat("\nDuplicada\n")
print(m)
print(f)
d <- as.numeric(out[1,2])
cat("\td de Cohen (es.dif::es.d) =", d,"\n")
print(effectsize::interpret_d(d,rules = "cohen1988"))
print(effectsize::interpret_d(d,rules = "sawilowsky2009"))
print(effectsize::interpret_d(d,rules = "gignac2016"))
print(effectsize::interpret_d(d,rules = "lovakov2021"))
d <- psych::cohen.d(estatura,grupo)$cohen.d[2]
cat("\td de Cohen (psych::cohen.d) =", d,"\n")
print(effectsize::interpret_d(d,rules = "cohen1988"))
print(effectsize::interpret_d(d,rules = "sawilowsky2009"))
print(effectsize::interpret_d(d,rules = "gignac2016"))
print(effectsize::interpret_d(d,rules = "lovakov2021"))
cat("\nSelecao de modelo\n")
R2aj <- (F-1)/((F-1)+df+1)
cat("\tR^2 ajustado =", R2aj,"\n")
omega2 <- (F-1)/((F-1)+df+2)
cat("\tomega^2 = ", omega2,"\n")
print(o2 <- effectsize::omega_squared(fit2)$Omega2)
cat("\tomega^2 (effectsize::omega_squared) = ", o2,"\n\n")
sink()

